### ISSUE TITLE
help with changes to remove "members"

### ISSUE THREAD

**Issue by angelslacerda** [Hitman666/IonicShoppingTodoFirebaseMaterial#1]
I am new to programming and I'm preparing my first application. I would like an aid, as this application has a good basis for what I want to do in my application.

I need to make some changes to all users to log in to access the entire list "groups", not only the user added. But I want the Firebase keep track of who entered the items in the database.

**Comment by NikolaBreznjak** [comment]
And what have you done so far?

**Comment by angelslacerda** [comment]
Because the code has a lot of information, I was trying to track down where the filter is used, analyzing the code backwards. I think I have to work on .factory ('Groups'), the "byUser". The problem is that it has several lines of code that I am not able to understand. For example the part of "userGroupsSnapshot". If you can give me any light where I should work, it is of great help. Spend some time working on a part of the code is to find out what I was looking at the wrong place is very discouraging.
